apiVersion: v1
kind: Secret
metadata:
  name: foodieexpress-secret
  labels:
    app: foodieexpress
type: Opaque
data:
  # Base64 encoded values:
  # JWT_SECRET_KEY: "foodieexpress-k8s-jwt-secret-key-2024"
  JWT_SECRET_KEY: Zm9vZGllZXhwcmVzcy1rOHMtand0LXNlY3JldC1rZXktMjAyNA==
  
  # MONGO_URI: "mongodb://mongodb-service:27017/foodieexpress"
  MONGO_URI: bW9uZ29kYjovL21vbmdvZGItc2VydmljZToyNzAxNy9mb29kaWVleHByZXNz
